### ISSUE TITLE
Can we add limit to allure history?

### ISSUE THREAD

**Issue by AndriiZhydkykh** [mmisty/cypress-allure-adapter#105]
Hello, Taisia. I hope you're doing well
Currently, we can see 20 runs in the trend and history, but is it possible to set this parameter to 10 or some other number? Thank you in advance for your attention to this

**Comment by mmisty** [comment]
> Hello, Taisia. I hope you're doing well
> 
> Currently, we can see 20 runs in the trend and history, but is it possible to set this parameter to 10 or some other number? Thank you in advance for your attention to this 
> 
> 

Hello, @AndriiZhydkykh 
I assume you are talking about Allure Report. 
Actually, allure report history is something that is being controlled by previous runs. Take a look how it is done https://allurereport.org/docs/history-and-retries/#how-to-enable-history 
This plugin helps to create json files for test run, but not report itself.

**Comment by AndriiZhydkykh** [comment]
Thanks for this link. I saw that the default state is 20 and we cannot change this state. And I thought maybe there is some function in your version of the plugin that can help change this setting.

**Comment by mmisty** [comment]
@AndriiZhydkykh 
Unfortunatelly, there allure report generation has nothing common with json files that this plugin generates.

If you need just to see latest history trend that contains N results before generating report you could delete extra results from `allure-results/history/history-trend.json` which looks like: 
```json
[ 
  {"data":{"failed":3,"broken":0,"skipped":0,"passed":3,"unknown":0,"total":6}},
  {"data":{"failed":3,"broken":0,"skipped":0,"passed":3,"unknown":0,"total":6}}
]
```

**Comment by AndriiZhydkykh** [comment]
Okey, thank you. I will try it.
