### ISSUE TITLE
History not showing

### ISSUE THREAD

**Issue by fauzisunarya** [mmisty/cypress-allure-adapter#106]
hello, please help, how do I bring up the history of failed and successful tests, I looked at the example you posted on the github page, there you can see the history, but when I try there is no history,

**Comment by mmisty** [comment]
@fauzisunarya hello

Allure report history is something that is being controlled by previous runs. Take a look how it can be enabled https://allurereport.org/docs/history-and-retries/#how-to-enable-history

Just to let you know, @mmisty/cypress-allure-adapter plugin helps to create json files for a test run (to build report later), but not a report itself.

**Comment by fauzisunarya** [comment]
Hello @mmisty please help, I need to attach a video when the test is successful or failed, I have adjusted the configuration in cypress.config.js but there is no change, the video when the test results are successful and failed is not attached to the allure report, and is not generated in the video folder in project, is there a solution?


![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/527b3668-0fc2-497e-adeb-a978cff06878)

**Comment by mmisty** [comment]
@fauzisunarya is video problem related to history? did you solve history problem?

regarding video I suggest to check cypress documentation 

![image](https://github.com/mmisty/cypress-allure-adapter/assets/16957275/b2e91818-2dec-4a2e-8b27-0d14347a851c)

**Comment by fauzisunarya** [comment]
hello @mmisty thanks, for vidio success attach if test result passed, for history not showing, i already try, but stay not showing history, can you help me for detailed tutorial ?

**Comment by mmisty** [comment]
@fauzisunarya I've sent the link with documentation how to enable history. Did you try doing things that described there? if the problem persists I suggest googling errors, since the problem of not shown history is not the problem of this plugin.

**Comment by fauzisunarya** [comment]
hello, thank you for the answer @mmisty , so does the history test have to be done manually and not automatically generated? Do you know how to make the history automatically generated?

**Comment by mmisty** [comment]
@fauzisunarya I suggest creating script inside package.json to copy necessary files before building a new allure report

**Comment by fauzisunarya** [comment]
Can you attach an example of the script, because I don't understand if there is no detailed example, please help me, because I need it

**Comment by mmisty** [comment]
@fauzisunarya I do this plugin at my free time, but your questions are  not related to the plugin. I have already sent all the information you need to solve your problem. If you want detailed examples and individual work we can discuss the terms of consultation
