### ISSUE TITLE
Ability to exclude certain tests from the report based on a condition?

### ISSUE THREAD

**Issue by jprealini** [mmisty/cypress-allure-adapter#107]
Is there any way to tell the adapter to NOT include certain tests based on some condition? 

The scenario is that under some conditions, I am skipping some tests doing something like:

```
it("test", () => {
  if(condition) {
    test code
  } else { 
    cy.log("This test does not apply for condition")
  }
})
```

But I would need to tell Allure to directly NOT include it in the report, instead of outputting some message to cy.log... 

Is that possible?

Thanks

**Comment by mmisty** [comment]
Hello, @jprealini 
This seems to be overcomplicated.
To have only tests you want to see in report I would recommend to run only those tests with  `allure` env var set to `true`
And if you need to run other tests without including them in the report run them with  `allure`: `false`. 
To achieve that you can use [@mmisty/cypress-grep](https://www.npmjs.com/package/@mmisty/cypress-grep) package - it filters tests quickly by tags or test/suite title
