### ISSUE TITLE
Gherkin cucumber no detect 

### ISSUE THREAD

**Issue by fauzisunarya** [mmisty/cypress-allure-adapter#110]
hello, please help. I tried implementing gherkin using gherkin from "cypress-cucumber-preprocessor/steps", after generating allure the results were not suitable, is there a solution?

![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/7eb3f783-ee36-4fcd-a293-62531a89fdda)

![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/12f369c2-544b-41ab-9d57-32dbc73d0dfd)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/b3ce58e5-7367-48cc-a665-013cdeb3a20b)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/3f948851-1b84-4771-b919-f4cc244ee65a)

**Comment by mmisty** [comment]
@fauzisunarya hello, there is emample that works with cucumber in documents, could you please check it: https://github.com/mmisty/cypress-allure-adapter-example/tree/main/examples/cypress-js-gherkin

And also please check this link: https://github.com/mmisty/cypress-allure-adapter/blob/HEAD/docs/gherkin.md

Let me know how f you still have issues after checking the docs.

**Comment by mmisty** [comment]
closing since no updates
