### ISSUE TITLE
Sometimes Suites are not being shown correctly

### ISSUE THREAD

**Issue by jprealini** [mmisty/cypress-allure-adapter#111]
I have this framework that mixes cypress-each with cy-grep and allure

By using cypress-each, I run the same suite N times, once for each kind of user I have. 

By using cy-grep (From Gleb B. package) I target certain suites on each test run.

So, the way I am running this should end up showing me the Allure report with the same suite repeated N times (each with a distinct suffixed value I use to identify each iteration).

The weird thing is that sometimes it does, but sometimes, for the first iteration, Allure shows me the "parent describe block" title, instead of the one I am intending to see. 

To make this more clear, here I share a couple of screenshots.

This is for example my code for the Translations suite:

![image](https://github.com/mmisty/cypress-allure-adapter/assets/7246755/1a9b120a-37b7-48d7-8d97-7625d1b6cfae)

This is my report:

![image](https://github.com/mmisty/cypress-allure-adapter/assets/7246755/7e143339-308f-4612-82e8-44dba1b0ae25)

As you can see, there is one suite called "Translations". I would expect to see that one as parent to all the others... but no. Translations contains the tests for what would be my first iteration. And then the rest are displayed separately

Any ideas what could be causing this?

**Comment by jprealini** [comment]
I took me writing this issue to think about what I was doing... 
At the end, it was a misunderstanding on how to use cy.allure().parentSuite() and cy.allure().suite() in my specs.... 

I have this working now... 

![image](https://github.com/mmisty/cypress-allure-adapter/assets/7246755/b3f395ac-e37b-4826-b32a-8af69d4d8e03)

**Comment by mmisty** [comment]
@jprealini Great! I love such issues:) Good luck!

**Comment by jprealini** [comment]
Sorry @mmisty opening this again... I realized that prior to seeing the broken report and applying cy.allure() commands, the report was showing correctly. For some reason at some point this broke and I have no idea why... 
Any chance you can look at my code and maybe throw some ideas?

thanks

**Comment by mmisty** [comment]
@jprealini hello
If you want the same structure as suites structure, you can try deleting cy.allure().suite/parentSuite/subSuite run tests again and check the results - correct structure should be automatically created

**Comment by mmisty** [comment]
@jprealini you can also check examples here https://github.com/mmisty/cypress-allure-adapter-example

and example of report https://mmisty.github.io/cypress-allure-adapter-example/#suites


![image](https://github.com/mmisty/cypress-allure-adapter/assets/16957275/ef67ff5a-2a01-4f6b-85da-02fbdce2b221)

**Comment by mmisty** [comment]
@jprealini  Hello, could you please check latest version 0.16.5 - this issue may be fixed there

Closing it for now

**Comment by jprealini** [comment]
@mmisty hey! Yep... that did it... what was the issue about? Just by curiosity... :D 
Thanks!

**Comment by mmisty** [comment]
@jprealini  that was related to this issue https://github.com/mmisty/cypress-allure-adapter/issues/112
and to implicit update of ws package on 28th of April (so it started failing after 28th)
