### ISSUE TITLE
Authentication allure

### ISSUE THREAD

**Issue by fauzisunarya** [mmisty/cypress-allure-adapter#122]
hello, can you add authentication before accessing the allure report, you have to log in first?

**Comment by mmisty** [comment]
@fauzisunarya I'm not sure what are you talking about
This plugin doesn't have any authentication. It only helps to generate allure results, from which you can afterwards generate [Allure Report ](https://allurereport.org/docs/)

**Comment by fauzisunarya** [comment]
I mean, I request to add a login page, is that possible sir?

**Comment by mmisty** [comment]
this plugin doesn't have any html generation or html pages. It generates **only json files in a proper format** for Allure Report to be able to read it. Allure Report is something that I cannot control - it is [separate library](https://www.npmjs.com/package/allure-commandline). If you want something to be added there you should ask them about it. 

I addition I want to say that your request is quite strange:  to have login page you need to have a server where login information will be stored, but Allure Report is html with some javascript, it doesn't have any server. If you want to login before accessing the report you need to have your own server for that and implement auth logic there. Or as other option you can use paid version of allure which is called [Allure TestOps](https://qameta.io/).

**Comment by fauzisunarya** [comment]
Thank you for the confirmation, I have read about Allure Test Ops, but there is no method or example of a project that uses Cypress, how to implement a Cypress project using Allure Test Ops

**Comment by mmisty** [comment]
there is no difference which test framework you use - cypress, jest, mocha etc. Allure Testops will use generated json files by adapter (which is this plugin helps with). So it is enough for you read Allure TestOps documentation to understand how it should be setup. Also you can use chatGPT, it knows a lot about that.

**Comment by fauzisunarya** [comment]
OK, thank you sir.
You really helped me as a beginner, I hope your luck goes smoothly
