### ISSUE TITLE
how show environment 

### ISSUE THREAD

**Issue by fauzisunarya** [mmisty/cypress-allure-adapter#123]
hallo sir, please help me how to display the environment, is there an example of the settings?

example your project
![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/88e74602-8d45-4321-b1e2-afb1c0369bc9)

my project 
![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/5883c1c5-4873-44e8-82eb-565dbc0c7454)

**Comment by mmisty** [comment]
Hello, 

here is configuration for the example - all you see in the report is in the code.

https://github.com/mmisty/cypress-allure-adapter-example/blob/main/examples/cypress-js/cypress.config.js

**Comment by mmisty** [comment]
P.s. Could you please create discussion in case it is not a problem with the plugin
