### ISSUE TITLE
How to hide senstive information

### ISSUE THREAD

**Issue by fauzisunarya** [mmisty/cypress-allure-adapter#124]
Can Allure Report hide sensitive information, such as URLs, usernames, passwords, because this report is accessed publicly, I don't want other people to know this information?

![image](https://github.com/mmisty/cypress-allure-adapter/assets/43233727/71c980b6-2ba3-467b-9062-bffdd9873a45)

**Comment by mmisty** [comment]
Report will not be accessed publicly unless you serve it on a public web server. 

Anyways, plugin doesn't know what is sensitive information what is not, but it has setting to disable logging for specific commands - allureSkipCommands
you can read about it in documentation - Environment Variables

**Comment by fauzisunarya** [comment]
OK, thank you for the info sir
