### ISSUE TITLE
Incomplete Allure Reporting on Errors in before and after Hooks

### ISSUE THREAD

**Issue by chaitanyarajugithub** [mmisty/cypress-allure-adapter#149]
**Description:**
There is an issue with the Allure reporting in our Cypress tests where failures in the before and after hooks are not being logged correctly. Specifically:

**Error in before Hook:**
When an error occurs in the before hook, Cypress stops executing further tests in that suite.
The after hook still executes for cleanup purposes.

**Execution of after Hook:**
If the after hook executes without any errors, Allure correctly logs the failure details from the before hook.
However, if the after hook also encounters an error, Allure does not properly log the failure details from both the before and after hooks. This results in incomplete error reporting in Allure.

**Steps to Reproduce:**
Create a Cypress test suite with before and after hooks.
Introduce an error in the before hook.
Ensure the after hook also encounters an error.
Execute the test suite and observe the Allure report.

**Expected Result:**
Allure should correctly log the errors from both the before and after hooks.

**Actual Result:**
Allure logs the failure details from the before hook correctly if the after hook executes without errors.
If the after hook also fails, Allure does not log the errors correctly, leading to incomplete reporting.

**Comment by chaitanyarajugithub** [comment]
![image](https://github.com/mmisty/cypress-allure-adapter/assets/44492694/1cc34feb-13ec-4de1-ac53-855f7db50c66)

**Comment by mmisty** [comment]
I see that cypress itself cannot stand this behavior - and it doesn't output error 
<img width="558" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/002c889a-c490-4a38-bc71-8af74efd1149">
I'll trye to fix for adllure, but seems it is not so easy
I would suggest better do everything in before hooks

**Comment by chaitanyarajugithub** [comment]
Thanks for the quick response @mmisty . Please try from your end, until then I will modify my code.
But if we can fix that, it would be helpful.

**Comment by mmisty** [comment]
@chaitanyarajugithub JFYI,  this is related to cypress issue (which I've just created) https://github.com/cypress-io/cypress/issues/29762

**Comment by mmisty** [comment]
should be fixed in v2.0.10

**Comment by chaitanyarajugithub** [comment]
Thanks @mmisty for your quick support.
