### ISSUE TITLE
Gherkin keywords wrapped within session command after 2.3.0

### ISSUE THREAD

**Issue by mysticdevx** [mmisty/cypress-allure-adapter#169]
**Describe the bug**
The issue is aboout cypress-cucumber framework. The gherkin keywords are wrapped within the cy.session command, if its used. The issue is not observed in 2.1.0, when i upgrade t0 2.3.0 it statred appearing. (dint check the releases in between) 
The detailed v2.1.0 and 2.3.0 SS is attached to see the issue and difference.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade to 2.3.0
2. Use cy.session command in any of the step
3. Observe the following gherkin steps in html report

**Expected behaviour**
Gherkin steps should not be wrapped within the cy.session command. Expected is the behaviuor of v2.1.0

**Actual behaviour**
Gherkin steps are placed within the cy.session command.

**Screenshots**
See attached please.

**Desktop:**
 -  cypress-cucumber-preprocessor, TS
 - Browser electron and chrome
 - @mmisty/cypres-allure-adapter version 2.3.0
 - cypress version 13.12.0
 - OS: both on mac and gitlab docker runners
 
<img width="1684" alt="Screenshot 2024-07-03 at 07 38 50" src="https://github.com/mmisty/cypress-allure-adapter/assets/49609497/e7b7b091-c9c9-4788-8dad-81b21ec19d32">

**Comment by mmisty** [comment]
@mysticdevx thank you for reporting this! will fix

**Comment by mmisty** [comment]
Is this correct that you have gherkin steps within session command?

**Comment by mmisty** [comment]
if it is possible could you please also attach test text

**Comment by mysticdevx** [comment]
> Is this correct that you have gherkin steps within session command?

nope, gherkin steps as usual. no gherkin steps are nested, all are in the same level. In the screenshots, the `cy.session` is in the implementation of `Given` step. Therefore, alhhough `Then` and `And` steps are two distinct steps, in v 2.3.0 they are shwon as if they are inside the `given` step.
Thanks.

**Comment by mysticdevx** [comment]
> if it is possible could you please also attach test text

sorry, wanted to supply an example in a small repo, please see the step, and repo [here the step](https://github.com/mysticdevx/cy-allure-adapter/blob/main/cypress/e2e/steps/all.steps.ts#L25) and 3rd scenario [here.](https://github.com/mysticdevx/cy-allure-adapter/blob/main/cypress/e2e/features/regular-feature.feature) 
Also, for convenience i have included the created html report, so that u can see without running.
Thanks again!

**Comment by mmisty** [comment]
this should be fixed in 2.3.1
