### ISSUE TITLE
Gherkin phrases are being nested

### ISSUE THREAD

**Issue by Alvis-pixel** [mmisty/cypress-allure-adapter#214]
**Describe the bug**
After upgrade to 2.6.1, my allure report shows with nested Gherkin phrases. I had to revert all the way to 2.2.2 before phrases are listed as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a Cypress Cucumber test with @badeball/cypress-cucumber-preprocessor
2. npx allure serve

**Expected behaviour**
Report containing Gherkin execution steps in a list

**Actual behaviour**
Report containing Gherkin execution steps in a list, but nested underneath each other. see screenshot

**Screenshots**
![image](https://github.com/user-attachments/assets/7454033c-1ac9-4010-890e-ccb591b4ccf7)

**Desktop (please complete the following information):**
 - language typescript
 - Browser Chrome headless
 - @mmisty/cypres-allure-adapter version 2.6.1
 - cypress version 13.13.2
 - OS: GitLab CI/CD Pipeline

**Attachments**
 
**Workaround**

Does the issue have workaround? [ yes / no ]
Yes, revert cypress-allure-adapter to version 2.2.2

**Additional context**

**Comment by mmisty** [comment]
@Alvis-pixel thank you for reporting this, in the progress of fixing.

**Comment by mmisty** [comment]
Could you please check 2.6.3 version, should be fixed there

**Comment by Alvis-pixel** [comment]
It looks good in 2.6.3, thank you!
