### ISSUE TITLE
Enhancement: Add "Feature:" title in Gherkin feature files as features in results

### ISSUE THREAD

**Issue by Alvis-pixel** [mmisty/cypress-allure-adapter#218]
I would request the following enhancement:

When using cucumber preprocessor ("@badeball/cypress-cucumber-preprocessor") with cypress, I think it would be relevant for the feature title to be added as feature in allure results:

"Feature: A feature I want to test"

Workaround today:

In order to define a feature in the file contents as a feature, you have to use the "@feature("")" tag in the feature file.
If you're using badeball as preprocessor, it will work with the tag, but it will be ugly because whitespaces aren't allowed in tags:

"@feature("A_feature_I_want_to_test")"

There could be multiple "Features" in a feature file also, i.e. each time the "Feature:" title is used.

**Comment by mmisty** [comment]
Hello, @Alvis-pixel 

I would need to think about that whether we need to add it into plugin 

but for now you can add this into your setup file (be aware it will not add features on `before` hooks failure : 

```javascript
beforeEach(function () {
  cy.readFile(Cypress.spec.absolute, { log: false }).then(text => {
    const match = text.match(/^Feature: ([^\n]*)$/m);

    if (match && match[1]) {
      cy.allure().feature(match[1]);
    }
  });
});
```

**Comment by mmisty** [comment]
Update: Feature is a suite name, so it can be simplified: 

```javascript
Cypress.Allure.on('test:started', test => {
  if (test.parent?.title) {
    Cypress.Allure.feature(feature);
  }
});

```

**Comment by mmisty** [comment]
with this it is better add this on you side which you can control better
Closing it for now.

**Comment by Alvis-pixel** [comment]
> Update: Feature is a suite name, so it can be simplified:
> 
> ```js
> Cypress.Allure.on('test:started', test => {
>   if (test.parent?.title) {
>     Cypress.Allure.feature(feature);
>   }
> });
> ```

This one didn't work for me, or I didn't understand. Add in a setup spec, or cypress.config.ts? Also, "Cannot find name 'feature'"

**Comment by mmisty** [comment]
Ops, sorry 
this should go to setup file:
```
Cypress.Allure.on('test:started', test => {
  if (test.parent?.title) {
    Cypress.Allure.feature(test.parent?.title);
  }
});
```
