### ISSUE TITLE
Support suite command

### ISSUE THREAD

**Issue by MDzyga** [mmisty/cypress-allure-adapter#25]
Hi,
Will you support suite command as shelex package?

**Comment by mmisty** [comment]
Hi @MDzyga , 
I will do that with pleasure. Could you please explain what is missing in more details?
Do uyou mean adding these commands in API ? 
```
parentSuite(name: string)
suite(name: string)
subSuite(name:string) 
```

**Comment by MDzyga** [comment]
do you know when you will be able to release a version with this/these method(s)?

**Comment by mmisty** [comment]
in the meantime as a workaround you can use
```
cy.label('parentSuite', 'Parent Suite name here');
cy.label('suite', 'Suite name here');
cy.label('subSuite', 'Sub Suite name here');
```

**Comment by MDzyga** [comment]
ooo nice :)
We use it to group our tests on Suites panel.

Currently it looks like
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/cbc37add-e8df-47a7-8c9b-00a75095dfef)

When we used suite method from shelex it looks like
![image](https://github.com/mmisty/cypress-allure-adapter/assets/38663990/69b92199-8808-46ec-9470-fa02ca588b9a)

**Comment by mmisty** [comment]
> ooo nice :) We use it to group our tests on Suites panel.
> 
> Currently it looks like ![image](https://user-images.githubusercontent.com/38663990/266286405-cbc37add-e8df-47a7-8c9b-00a75095dfef.png)
> 
> When we used suite method from shelex it looks like ![image](https://user-images.githubusercontent.com/38663990/266286455-69b92199-8808-46ec-9470-fa02ca588b9a.png)

I got your concern, 
Could also please send you test file structure
Actually in this plugin it should automatically add suite labels depending on your 'describes'

For example 

```javascript

describe('suite', () => {
  describe('child', () => {
    it('test', () => {
      //
    });
  });
});
```

should create report with suites `suite` -> `child`

**Comment by MDzyga** [comment]
ok, currently it looks like

```
describe
  describe
    it
      suite 1
    it
      suite 1
  describe
   it
      suite 2
   it
     suite 3
   it
     suite 4
```

**Comment by mmisty** [comment]
So referring to screenshot is it actual structure in you spec file?  

```javascript
describe('Configuration', () => {
  describe('QLC-232 - Create or update configuration', () => {
    // tests
  });
  
  describe('QLC-235 - Get All configurations', () => {
      // tests
   });
  
  describe('QLC-237 - Get Configuration (by name)', () => {
      // tests
   });
  // ...
});
```

**Comment by MDzyga** [comment]
Not exactly
```
describe('Configuration', () => {
  describe('Get operations', () => {
    it('get one', () => {
       cy.suite('QLC-232 - Create or update configuration')
    })
    
    it('get all', () => {
       cy.suite('QLC-232 - Create or update configuration')
    })
  });
  
  describe('Save operations', () => {
    it('save', () => {
       cy.suite('QLC-235 - Get All configurations')
    })
   });
  // ...
});
```

**Comment by mmisty** [comment]
@MDzyga 0.10.0 version has been released. You can check the [documentation](https://github.com/mmisty/cypress-allure-adapter/blob/main/docs/interface.md#suite) for details.

**Comment by mmisty** [comment]
@MDzyga From what I see seems it is better to use epic/feature/story
After using that you will see results grouped on Behaviours tab

```
describe('Configuration', () => {
  describe('Save operations', () => {
    it('create', () => {
       cy.allure().story('QLC-232 - Create or update configuration')
    })
    
    it('update', () => {
       cy.allure().story('QLC-232 - Create or update configuration')
    })
  });
  
  describe('Get operations', () => {
    it('get all', () => {
       cy.allure().story('QLC-235 - Get All configurations')
    })
   });
  // ...
});
```

<img width="802" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/7d5ef8a1-16b4-46cd-9ec4-cfa824376ac2">

and in the same time they will be groupped by suites: 
<img width="808" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/87175c6b-daaf-4d20-be94-ffd5246a26d6">

**Comment by MDzyga** [comment]
Thank you very much :) 
I will discuss with tester about your proposal :)
