### ISSUE TITLE
Manager folder structure in allure test Ops

### ISSUE THREAD

**Issue by jeremie-val** [mmisty/cypress-allure-adapter#37]
It's more likely a evolution rather than a bug, but : 

When using Shelex plugin, we have an organization of our test through describe and it. 
![image](https://github.com/mmisty/cypress-allure-adapter/assets/79636114/4b53bcbc-4c78-48f1-bd5b-ac658a49b977)

The folder structure is compose from the different describe and it function : 
![image](https://github.com/mmisty/cypress-allure-adapter/assets/79636114/d3ac4083-cefe-4a5b-8ae3-7b2d27c331de)

When switching to your library, we've lost this structure : 
![image](https://github.com/mmisty/cypress-allure-adapter/assets/79636114/2fd9f173-fe49-45fc-921f-3e6b76601145)

To see this structure, you need to use the "Suites" section on a launch (in the "Tree" tab)
![image](https://github.com/mmisty/cypress-allure-adapter/assets/79636114/3aedbf7d-69f5-4504-823b-d24f956e89e2)

Any advice on how to retrieve this type of organization ?

**Comment by mmisty** [comment]
Hello @jeremie-val, the structure should be the same in your allure report
Here is example report: https://mmisty.github.io/cypress-allure-adapter-example/#suites/4cbe1681a5869c86fbcf55b2b7d6abe3/494d8b86f8774008/

For Allure Testops I added tree structure in project like: 
<img width="298" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/45d3a4f5-025f-41be-9f16-5877f5b11893">

#### To do so: 

In administration section -> Custom Fields you need to add `Parent suite`, `Sub suite` and `Suite`
In project administration -> Custom Fields you need to add mapping for these fileds: 
<img width="109" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/db12e45b-f6b9-4bc9-aeda-08cf36e48c97">
<img width="195" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/63d0f46f-2a97-4b2c-9746-61d02248b650">
<img width="147" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/576d8445-de5e-4759-bf8c-ef6f9eb5b5e0">
And after that you can update tree settings on Trees tab for project to: 
<img width="310" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/484ddeeb-ce26-45a7-8182-6e7b27e76918">

**Comment by mmisty** [comment]
@jeremie-val added this into documentation https://github.com/mmisty/cypress-allure-adapter/blob/main/README.pack.md#suites-tree

**Comment by jeremie-val** [comment]
Thank you @mmisty
So I need to update our tests to add some cy.allure() call to add name for suite, subsuite and parentsuite.

**Comment by mmisty** [comment]
@jeremie-val, no, you don't need to update tests - those labels are being added automatically basing on `describe`'s structure.
You just need to update Allure Testops custom fields as wrote above.

**Comment by jeremie-val** [comment]
Thanks for your reply. 
On my side, if I don't add this call, I don't see the organization.

What you're telling is that if I have some describe inside another one, I should see the organization level ?

**Comment by mmisty** [comment]
@jeremie-val right, like in [example report](https://mmisty.github.io/cypress-allure-adapter-example/#suites/4cbe1681a5869c86fbcf55b2b7d6abe3/494d8b86f8774008/) - there is test file attached for current test on the screenshot:
 
<img width="1128" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/20edd23d-3fe8-4bcd-afcd-cb4e32cf9594">

You can also check your configuration  - should be similar to this (for javascript) https://github.com/mmisty/cypress-allure-adapter-example

**Comment by jeremie-val** [comment]
I've seen my mistake, and now it's perfect ! 
Thanks :) 

We can now upgrade to Cypress V13
