### ISSUE TITLE
Test status failed after error in before hook

### ISSUE THREAD

**Issue by Paprikh7** [mmisty/cypress-allure-adapter#42]
Hi,
I am getting a failed status after failing some prerequisites in the before hook. I would expect to have a **broken** status or something else because the test didn't even start. It also didn't write the name of the test suite (describe), but just the root suite.
It also doesn't log anything that happened in before hook also.
![Screenshot 2023-10-05 at 15 42 51](https://github.com/mmisty/cypress-allure-adapter/assets/109957805/87d491ed-4809-4594-a3fd-bc6054036f21)

**Comment by mmisty** [comment]
@Paprikh7 could you please send text of your test, and also version of plugin you use

**Comment by mmisty** [comment]
@Paprikh7 thank you for reporting, I'll be near computer in several hours will take a look then.

**Comment by mmisty** [comment]
@Paprikh7 I cannot see any problems, spec that you have sent should work fine in case of errors. I will check that again.
But from the first screenshot It seems you have sent different test text, not the one which failed.
could you please sent the exact spec file contents that failed if that is possible

**Comment by mmisty** [comment]
@Paprikh7 do you have any before hooks in setup files (outside of spec file)?

**Comment by Paprikh7** [comment]
Only this in e2e:
```javascript
before(function(){
    cy.allure().startStep('ignore-allure-log')
    if (Cypress.env('TCIWillBeExecuted') === 'no'){
        Cypress.runner.stop()
        cy.task("log", `TCIWillBeExecuted in test data is :${Cypress.env('TCIWillBeExecuted')}`);
    }
    cy.allure().endStep()
})
``` 
Update screenshot with same code from above:
![Screenshot 2023-10-05 at 16 54 55](https://github.com/mmisty/cypress-allure-adapter/assets/109957805/64ef2efe-aee4-4cf5-9237-cd968dfec34d)

**Comment by mmisty** [comment]
@Paprikh7 I think the problem is that you stop cypress runner. why would you do that? what do you try to achieve?
I wouldn't expect correct work when cypress runner is stopped.

**Comment by mmisty** [comment]
@Paprikh7  I tried to reproduce the issue and it works fine for me: 

<img width="600" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/ebbe9637-4ee4-4826-8421-0d6bf9eb03c6">
I ran this spec: 
<img width="488" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/cad5510c-f212-4e77-aee4-776dc26eb236">

And I got this result:


<img width="1420" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/4d2f312e-c7b8-4d12-8255-45b62b45f2b3">


So to have more information why this didn't work for you: 
 - please send `e2e.ts` or `e2e.js` file contents
 - please send `package.json` file contents
 - please send command with which you started your tests
 -  does this `TCIWillBeExecuted` env variable was set to `no` when you have unexpected result?

**Comment by Paprikh7** [comment]
```javascript
    if (Cypress.env('TCIWillBeExecuted') === 'no'){
``` 
It means if in json data is NO, do not even start the test.
Even if I comment this before still getting root suite.

e2e.js
```javascript
// ***********************************************************
// This example support/index.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// Import commands.js using ES2015 syntax:
import './commands';
import '@mmisty/cypress-allure-adapter/support';

import { Exporter } from "./utils/Exporter";
let exporter = new Exporter({ clearAfterWrite: true });
Cypress.on('uncaught:exception', (err, runnable) => {
    // returning false here prevents Cypress from failing the test
    return false
})

import registerCypressGrep from '@cypress/grep/src/support'

import { testEndStatus } from "../e2e/TS/globalFunctions";
registerCypressGrep()
export const componentDeploy = {
    env: {
        shouldDeploy: false,
        tested: false
    },
    vms: {
        shouldDeploy: false,
        tested: false
    },
    lb: {
        shouldDeploy: false,
        tested: false
    },
    int_fw: {
        shouldDeploy: false,
        tested: false
    },
    ext_fw: {
        shouldDeploy: false,
        tested: false
    },
    caas: {
        shouldDeploy: false,
        tested: false
    },
    ipsecTunnel: {
        shouldDeploy: false,
        tested: false
    },
    paasLPA: {
        shouldDeploy: false,
        tested: false
    },
    saasAPI: {
        shouldDeploy: false,
        tested: false
    }
}
export const testSuccessData = {
    success: true
}
Cypress.on('test:after:run', (test, runnable) => {
    cy.allure().startStep('ignore-allure-log')
    testEndStatus(test)
    cy.allure().endStep()
})
before(function(){
    cy.allure().startStep('ignore-allure-log')
    if (Cypress.env('TCIWillBeExecuted') === 'no'){
        Cypress.runner.stop()
        cy.task("log", `TCIWillBeExecuted in test data is :${Cypress.env('TCIWillBeExecuted')}`);
    }
    cy.allure().endStep()
})
afterEach(function () {
    exporter.writeFile(`cypress/reports/results/API_logs/${Cypress.spec.name}/${Cypress.currentTest.title}.json`);
});
// Alternatively you can use CommonJS syntax:
// require('./commands')
``` 
package.json
```javascript
{
  "name": "csp-fe",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "allure:filter": "node allure-filter.js",
    "cy:open:testSK": "cypress open --e2e --browser chrome --config-file cypress/configs/enviroment/config.v99test-be01-SK.js",
    "cy:open:testEN": "cypress open --e2e --browser chrome --config-file cypress/configs/enviroment/config.v99test-be01-EN.js",
    "cy:open:testSKsemi": "cypress open --e2e --browser chrome --config-file cypress/configs/enviroment/config.v99test-be01-semiautomat-SK.js",
    "cy:run:testSK": "cypress run --browser chrome --config-file cypress/configs/enviroment/config.v99test-be01-SK.js --spec cypress/e2e/${testFile} --env",
    "cy:run:testSKsemi": "cypress run --browser chrome --config-file cypress/configs/enviroment/config.v99test-be01-semiautomat-SK.js --env"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cypress/grep": "^3.1.5",
    "@faker-js/faker": "^8.0.2",
    "@mmisty/cypress-allure-adapter": "^0.11.0",
    "cypress": "^13.3.0",
    "cypress-mochawesome-reporter": "^3.5.1",
    "cypress-recurse": "^1.35.2",
    "cypress-wait-until": "^2.0.1",
    "eslint-config-prettier": "^8.9.0",
    "eslint-plugin-cypress": "^2.13.3",
    "eslint-plugin-prettier": "^5.0.0"
  },
  "dependencies": {
    "csvtojson": "^2.0.10",
    "moment": "^2.29.4",
    "papaparse": "^5.4.1",
    "prettier": "^3.0.0",
    "uuid": "^9.0.0"
  }
}
```
test.cy.js
```javascript
describe("Test suite name", { tags: "@test" }, function () {
  before(function() {
    cy.visit("/")
    cy.get("something")
  })
  it("Test name", function() {
    cy.visit("/")
  });
})

```  
<img width="1878" alt="Screenshot 2023-10-05 at 19 01 52" src="https://github.com/mmisty/cypress-allure-adapter/assets/109957805/01682de2-197e-4442-9bd7-1ff346f43350">
<img width="411" alt="Screenshot 2023-10-05 at 19 07 39" src="https://github.com/mmisty/cypress-allure-adapter/assets/109957805/28df53a9-af86-4b14-9cbf-260c0c79e775">

_please send command with which you started your tests_
```
npx cypress run --browser chrome --config-file cypress/configs/enviroment/config.v99test-be01-SK.js --spec "cypress/e2e/test.cy.js"
``` 
_does this TCIWillBeExecuted env variable was set to no when you have unexpected result?_
No it will just kill the cypress runner, so test won't even start. It's works fine

**Comment by mmisty** [comment]
@Paprikh7 I cannot replicate the issue, and I don't see something suspicious.
Could you please send logs that you will see in nodejs console after running test with env variable:
DEBUG=cypress-allure*

**Comment by Paprikh7** [comment]
config:
```javascript
const { defineConfig } = require('cypress');
const defaultSettings = require('../base')
const { configureAllureAdapterPlugins } = require("@mmisty/cypress-allure-adapter/plugins");

module.exports = defineConfig({
    ...defaultSettings.runConfig,
    e2e: {
        "types": [
            "cypress"
          ],
        ...defaultSettings.e2e,
        excludeSpecPattern: "cypress/e2e/semi-automatic/*.cy.js",
        baseUrl: "https://v99test-be01.local.sk.cloud",
        retries: 0,
        experimentalMemoryManagement: true,
        setupNodeEvents(on, config) {
            configureAllureAdapterPlugins(on, config);
            require('@cypress/grep/src/plugin')(config);
            on('before:browser:launch', (browser = {}, launchOptions) => {
                // the browser width and height we want to get
                // our screenshots and videos will be of that resolution
                const width = 1920
                const height = 1080

                if (browser.name === 'chrome' && browser.isHeadless) {
                    launchOptions.args.push(`--window-size=${width},${height}`)

                    // force screen to be non-retina and just use our given resolution
                    launchOptions.args.push('--force-device-scale-factor=1')
                }
                if (browser.name === 'firefox' && browser.isHeadless) {
                    launchOptions.args.push(`--width=${width}`)
                    launchOptions.args.push(`--height=${height}`)
                }

                // IMPORTANT: return the updated browser launch options
                return launchOptions
            })
            on('task', {
                log(message) {
                    console.log(message)

                    return null
                },
            })
            return config;
        },
        env: {
            "apiUrl": "https://v99test-be01.local.sk.cloud",
            "translation": "../support/language/skTranslation.json",
            "allure": "true",
            "allureResults": "../../../allure-results",
            "allureAddVideoOnPass": "true",
            "allureSkipCommands": 'intercept,before,then,testParameters,wrap,wait',
            "allureSkipSteps": '"after each" hook*,"before all","after all",ignore-allure-log',
        },
    }
})
```
default.settings
```javascript
module.exports = {
    runConfig: {
        videoCompression: 15,
        numTestsKeptInMemory: 50,
        video: true,
        trashAssetsBeforeRuns: false,
        viewportWidth: 1920,
        viewportHeight: 1080,
        defaultCommandTimeout: 10000
        },
        e2e: {
            chromeWebSecurity: false,
        }
}
``` 

log file:

 
[log.log](https://github.com/mmisty/cypress-allure-adapter/files/12825525/log.log)

**Comment by mmisty** [comment]
@Paprikh7 one problem seems resoved: 
> It also doesn't log anything that happened in before hook also.

you are skipping before all hook step, that's why it doesn't appear in your test. Seems I need to add status check - when step has non-passed status it will not be skipped.

The other problem with root suite still cannot be reproduced.

**Comment by Paprikh7** [comment]
Oops, I left 'before' in the skip steps, but even if I remove it.
```javascript
 env: {
            "apiUrl": "https://v99test-be01.local.sk.cloud",
            "translation": "../support/language/skTranslation.json",
            "allure": "true",
            "allureResults": "../../../allure-results",
            "allureAddVideoOnPass": "true",
            "allureSkipCommands": 'intercept,then,testParameters,wrap,wait',
            "allureSkipSteps": '"after each" hook*,"after all",ignore-allure-log',
        },
``` 
It's still doesn't log before.
![Screenshot 2023-10-06 at 11 17 32](https://github.com/mmisty/cypress-allure-adapter/assets/109957805/ac903cb9-50f6-434b-a910-0809b5197c2e)
Log without before in skipsteps
[log.log](https://github.com/mmisty/cypress-allure-adapter/files/12829246/log.log)

**Comment by mmisty** [comment]
@Paprikh7 what I see is that you have registered **5 reporters**  somehow (`specStarted` event is met 5 times in log), should be one. That's why events got mixed and you get what you get.
I recommend reviewing your setup once again since I don't have access to your codebase. 

If you still want this issue to be reviewed please create test repo that reproduces the problem.  Only after I get reproducible steps I could fix that.

For example repo you can use this one - [cypress-allure-adapter-example](https://github.com/mmisty/cypress-allure-adapter-example/)

**Comment by Paprikh7** [comment]
Okay, I found out what was happening with this thing. It's pretty dumb
I have in e2e.js:
```javascript
import { testEndStatus } from "../e2e/TS/globalFunctions";
export const testSuccessData = {
  success: true,
};
Cypress.on("test:after:run", (test, runnable) => {
  cy.allure().startStep("ignore-allure-log");
  testEndStatus(test);
  cy.allure().endStep();
});
```
 globalFunctions.js
```javascript
export const testEndStatus = (test) => {
  cy.allure().startStep("ignore-allure-log");
  if (test.state === "failed") {
    testSuccessData.success = false;
  }
  cy.allure().endStep();
};
``` 
When I comment this out of the code, everything works correctly. 
Also, it's interesting that in the old Shelex plugin, it was not a problem

**Comment by mmisty** [comment]
@Paprikh7 I recommend not importing anything from `e2e.js`, many plugins may work incorrectly in case when you import something from e2e.js inside your test or in other place. (in your case seems it is circular refernce)

Shelex's plugin worked fine in this cases since it has totally different architecture. Current plugin has it own reporting service (writes results right away) which is being registered in e2e.js, and it when register it several times - several services are being started. From my side I will think of ignoring all other registerings except the first one.

**Comment by Paprikh7** [comment]
@mmisty Okay, thank you :)
I would like to ask, why can't I use, for example, cy.allure().parentSuite() in the before hook? Because some things we are doing in the before hook can fail, and then I am not able to set testParameters or parentSuite, etc., because it would fail the whole test at the beginning, and the test sections won't be executed at all.

**Comment by mmisty** [comment]
@Paprikh7 for this purpose you can use events like described here https://github.com/mmisty/cypress-allure-adapter/blob/main/README.pack.md#startend-test-events

These events will be always fired even when failure in before hook - you can set all metadata there.
And if you have correct setup `parentSuite` label should be set automatically even when before hook fails.

**Comment by mmisty** [comment]
@Paprikh7 
1. regarding structure - I will check
2. Regarding events - events body is done synchronously so you can not use cy.allure in body of event, instead of it you need to use Cypress.Allure (like I sent in examples)
3. regarding loops for parameters I think better to add  cy.allure().parameter inside test body: 

```export function Tc_loginSmokeAdminGestor() {
  describe(`Login test`, function () {
 
    Object.values(loginTest).forEach((testData) => {
      it(`Login as ${testData.Username}`, () => {
        cy.allure().parameter(testData.Username)
        cy.testParameters(testData)
        login(testData.Username, testData.Password);
      });
    });
  });
}
```

**Comment by mmisty** [comment]
The other thing you can use to transfer data from test to Allure event is additional cypress configuration:
```describe('suite', () => {
  Cypress.Allure.on('test:started', test => {
    const param = test._testConfig.unverifiedTestConfig.myParameter;
    Cypress.Allure.parameter('num', param);
  });

  before(() => {
    throw new Error('ERR');
  });

  ['1', '2'].forEach(t => {
    it(`login ${t}`, { myParameter: t }, () =>  {
      cy.log('1243');
    });
  });
});

```

**Comment by mmisty** [comment]
@Paprikh7 
regarding hierarcy 
<img width="498" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/e89dfb49-4c10-4d59-8834-5561812fb429">

```javascript 
export const Tc_loginSmokeAdminGestor = () => {
  describe('smoke', () => {
    Cypress.Allure.on('test:started', test => {
      // console.log(test);
      const param = test._testConfig.unverifiedTestConfig.myParameter;
      console.log(param);
      Cypress.Allure.parameter('num', param);
    });

    ['1', '2'].forEach(t => {
      it(`login ${t}`, { myParameter: t }, function () {
        cy.log('1243');
      });
    });
  });
};

```

```javascript
export const Tc_test = () => {
  describe('test hierarchie', () => {
    it('testov', function () {
      cy.visit('/');
    });
  });
};

```

result: 
<img width="534" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/cc13fca6-257c-489d-a233-4aab02bf9fc6">
<img width="783" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/4139d4cd-6f0b-4358-b54b-7037d00fe852">


If you second test has other baseUrl than previous ones it can lead to some strange results since browser will reload.


Also I suggest not to combine this way (because of reasone above) - better to put the same suite name: 
----- 

```javascript
describe('Pipeline smoke Test', function () {
  describe('test hierarchie', () => {
    it('testov', function () {
      cy.visit('/');
    });
  });
});

```


```javascript
describe('Pipeline smoke Test', function () {
   describe('smoke', () => {
    Cypress.Allure.on('test:started', test => {
      // console.log(test);
      const param = test._testConfig.unverifiedTestConfig.myParameter;
      console.log(param);
      Cypress.Allure.parameter('num', param);
    });

    ['1', '2'].forEach(t => {
      it(`login ${t}`, { myParameter: t }, function () {
        cy.log('1243');
      });
    });
  });
});

```

And also there are many other ways to organize tests: packages tab (folder structure), behaviors tab  (epic/feature/story)

**Comment by Paprikh7** [comment]
Okay, thank you for your help
