### ISSUE TITLE
Unexpected state in beforeSpecHandler: test-finished, when using cucumber-preprocessor

### ISSUE THREAD

**Issue by mircea-marascu** [mmisty/cypress-allure-adapter#44]
I am using the cypress-cucumber-preprocessor from badeball and I am running into this issue after successfully running the first scenario from a feature file.

An error was thrown in your plugins file while executing the handler for the before:spec event.

The error we received was:

```
Error: Unexpected state in beforeSpecHandler: test-finished (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
    at createError (/Users/mirceamarascu/Projects/tal-ui-bridge-qa/node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/error.js:9:12)
    at beforeSpecHandler (/Users/mirceamarascu/Projects/tal-ui-bridge-qa/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js:190:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Disabling allure reporter works just fine, so the issue is not caused by the preprocessor.
Is this something you could fix? I really appreciate your effort in rebuilding this allure adapter.

Thanks!

**Comment by mmisty** [comment]
@mircea-marascu hello! 
I would love to make a fix if it's possible if you could provide reproducibility steps (your project setup, and etc).

Regarding issue that you are facing I would propose using [this solution](https://github.com/cypress-io/cypress/issues/5240#issuecomment-1139509828)  since both plugins use cypress events like 'before:run', 'after:screenshot'

**Comment by mmisty** [comment]
so it would be like: 
```typescript

export class EventForwarder {
  private emitter: EventEmitter;
  private task: Cypress.Tasks;
  public on: Cypress.PluginEvents;

  public constructor() {
    this.emitter = new EventEmitter();
    this.task = {};

    this.on = (action, arg) => {
      if (action === 'task') {
        Object.assign(this.task, arg);
      } else {
        this.emitter.on(action, arg as () => void);
      }
    };
  }

  public forward(on: Cypress.PluginEvents): void {
    for (const event of this.emitter.eventNames()) {
      on(event as any, async (...args: unknown[]) => {
        for (const listener of this.emitter.listeners(event)) {
          await listener(...args);
        }
      });
    }
    on('task', this.task);
  }
}


export default async function plugins(cyOn, config) {
    export const cyEventForwarder = new EventForwarder();
    const { on } = cyEventForwarder;
    // allure register with new 'on'
    configureAllureAdapterPlugins(on, config);

    // other plugins register with new 'on'
    // ...

    return config;
};
```

**Comment by mircea-marascu** [comment]
Hi @mmisty , thanks for fast replying, so I've created the class, imported the registerPlugins in the config file but I'm not sure how to use it, how to pass to it the cucumberPreprocessorPlugin. Here's my cypress.config.ts: 
`import {defineConfig} from "cypress";
import {addCucumberPreprocessorPlugin} from "@badeball/cypress-cucumber-preprocessor";
import browserify from "@badeball/cypress-cucumber-preprocessor/browserify";
import { configureAllureAdapterPlugins } from '@mmisty/cypress-allure-adapter/plugins';
import {registerPlugins} from "./cypress/plugins";

async function setupNodeEvents(
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
    on('file:preprocessor',
        browserify(config, {
            typescript: require.resolve("typescript"),
        })
    );
    await addCucumberPreprocessorPlugin(on, config);
    configureAllureAdapterPlugins(on, config);
    //await registerPlugins(on, config);
    return config;
}

export default defineConfig({
    e2e: {
        specPattern: "**/*.{feature,spec.ts}",
        numTestsKeptInMemory: 1,
        setupNodeEvents,
        env: {
            allure: true,
            allureResults: "cypress/results/allure-results",
            allureLogCyCommands: true,
            allureAddVideoOnPass: true,
        }
    }
});

`

**Comment by mmisty** [comment]
@mircea-marascu  should be something like that: 


```javascript
import {defineConfig} from "cypress";
import {addCucumberPreprocessorPlugin} from "@badeball/cypress-cucumber-preprocessor";
import browserify from "@badeball/cypress-cucumber-preprocessor/browserify";
import { configureAllureAdapterPlugins } from '@mmisty/cypress-allure-adapter/plugins';
import {registerPlugins} from "./cypress/plugins";

const cyEventForwarder = new EventForwarder();

async function setupNodeEvents(
    cyOn: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
    const { on } = cyEventForwarder;

    on('file:preprocessor',
        browserify(config, {
            typescript: require.resolve("typescript"),
        })
    );

    await addCucumberPreprocessorPlugin(on, config);
    configureAllureAdapterPlugins(on, config);
    //await registerPlugins(on, config);

    cyEventForwarder.forward(cyOn);

    return config;
}

export default defineConfig({
    e2e: {
        specPattern: "**/*.{feature,spec.ts}",
        numTestsKeptInMemory: 1,
        setupNodeEvents,
        env: {
            allure: true,
            allureResults: "cypress/results/allure-results",
            allureLogCyCommands: true,
            allureAddVideoOnPass: true,
        }
    }
});
```

**Comment by mmisty** [comment]
> Hey @mmisty, tried it, but I have this error now:
> 
> ![image](https://github.com/mmisty/cypress-allure-adapter/assets/13134996/da18610f-9092-4181-a9a1-f033c49598ce)
> 
> Any idea?
> 
> Thanks!

@mircea-marascu please add your e2e.ts file

**Comment by mircea-marascu** [comment]
![image](https://github.com/mmisty/cypress-allure-adapter/assets/13134996/3a5aa35b-c5fa-4db6-9462-cd4ef353b99e)

**Comment by mmisty** [comment]
Could you please try changing your 
setupNodeEvents (`on` to `cyOn` for file:preprocessor): 

```
async function setupNodeEvents(
    cyOn: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
    const { on } = cyEventForwarder;

    cyOn('file:preprocessor',
        browserify(config, {
            typescript: require.resolve("typescript"),
        })
    );

    await addCucumberPreprocessorPlugin(on, config);
    configureAllureAdapterPlugins(on, config);
    //await registerPlugins(on, config);

    cyEventForwarder.forward(cyOn);

    return config;
}
```

**Comment by mircea-marascu** [comment]
@mmisty , it worked! :) thanks a lot for the assistance!

Off topic: It would be great if you could make the Gherkin steps to wrap all the commands related to each step so we can have a clean report page per feature file when collapsing all of the feature steps. Something like that (I had to hide almost all of the commands):
<img width="880" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/13134996/77524954-38ed-4d61-8b5c-2b7d82e1e507">

**Comment by mmisty** [comment]
@mircea-marascu thank you for the suggestion!
I have planned to implement this in the nearest future.
Meanwhile this repo is open to PRs!

Also I appreciate any of your [support](https://github.com/mmisty/cypress-allure-adapter/blob/main/README.pack.md#support)
