### ISSUE TITLE
gherkin support

### ISSUE THREAD

**Issue by mysticdevx** [mmisty/cypress-allure-adapter#45]
Hey @mmisty,
Thanks for the plugin. It really helps a lot. Most probably, like many guys coming new here, I've also found this after the cypress-allure-reporter stopped working with new version of cypress (v12.15.0). 

The issue here is atm this plugin does not perform as expected with cucumber frameworks. Three main issues are there:
1- the grouping of suites and features does not work as expected.
2- the tags passed by .feature files are not recognised (i.e. issue links and suite tags)
3- in the test details, the gherkin steps are not shown explicitly, and commands are not grouped under their respective gherkin steps.

In the plugin roadmap, will there be cucumber support? (considering [this](https://github.com/Shelex/cypress-allure-plugin/issues/220) issue from the other plugin; may not be supported any soon, and [this](https://github.com/cypress-io/cypress/issues/27113#issuecomment-1683877922) issue comment in Cypress shows that the issue with `cy.now('task')` is not prioritised )

Thanks.

**Comment by mmisty** [comment]
Hello, @mysticdevx 
I'll add cucumber support in nearest time (this/next
week)
Could you please share what gherkin preprocessor do you use?

**Comment by mmisty** [comment]
@mysticdevx Also could you please share what is wrong with suites grouping? (please share your test, allure report screenshot and expected result)

**Comment by mysticdevx** [comment]
@mmisty yep definitely. 
The preporcessor that we are using is [this](https://github.com/badeball/cypress-cucumber-preprocessor) one with esbuild for better performance.
Shortly (maybe today or tomorrow) I will prepare a sample repo and post it here, with all possible scenarios so that u can see all the dependencies and tests, and I will commit the HTML created by the plugin. Additionally, I will prepare a list of present issues (either here or in the readme file, whichever u prefer). Also, I can commit a sample report created by the other plugin for reference. 
Thanks.

**Comment by mysticdevx** [comment]
> @mysticdevx Also could you please share what is wrong with suites grouping? (please share your test, allure report screenshot and expected result)

@mmisty I have prepared the repo [here](https://github.com/mysticdevx/cy-allure-adapter), and added a readme for all possible questions. If there's smt not clear, or to be tested I will be glad to help.
Thanks in advance for all your work.

**Comment by mysticdevx** [comment]
@mmisty update: I have pushed a new commit to the same repo with some changes. Shortly: I resolved the tags and report suites issues; however, I could not find a way to group Gherkin steps. Additionally, before and after hook fails are not reflected. I have modified the readme file for details.
