### ISSUE TITLE
How add all steps for failed tests?

### ISSUE THREAD

**Issue by AndriiZhydkykh** [mmisty/cypress-allure-adapter#47]
Hello, Taisia. Thanks for the wonderful plugin.
How I can see all steps for a failed test? At the moment, the report shows only successful steps, and the rest are missed. It would be very nice to see all the steps from the test plus the red-marked step that fell.
![image](https://github.com/mmisty/cypress-allure-adapter/assets/26884857/2f59c051-27ff-4de5-89d1-b3cf1889e00b)
For example, in this test, I have 6 steps + expected result. The test failed on the third step, but the third step and other steps after them are not displayed.

And is it possible to add information about steps only for failed tests, and not add information about steps and cypress commands for passed tests?

**Comment by mmisty** [comment]
@AndriiZhydkykh hello,
Actually failed steps should be added automatically as you can see in this example report https://mmisty.github.io/cypress-allure-adapter-example/

To understand why that didn't work for you could you please 
 - share what is your test
 -  your configuration (e2e.ts, plugins setup)  
 - environment variables 
 - how you start your tests 

Thank you

**Comment by AndriiZhydkykh** [comment]
Link to gitlab page https://allure-steps-example-andryzhidkikh-75825e16afa675914fb9248c80df.gitlab.io/
Link to gitlab repo -https://gitlab.com/andryzhidkikh/allure-steps-example
No failed steps are marked in red
![image](https://github.com/mmisty/cypress-allure-adapter/assets/26884857/839fccfa-903b-4814-878d-67db1d2d459d)

**Comment by mmisty** [comment]
@AndriiZhydkykh thank you! 

So I see that you have disabled cypress commands logging by `allureLogCyCommands: false`
You don't see failed commands because of that. Set it to `true`. 

if you want to see only your created steps you need to wrap cypress commands with allure steps: 
```
 it('.type() - type into a DOM element', () => {
    cy.allure().startStep('1.Step one');
    cy.get('.action-email').type('fake@email.com').should('have.value', 'fake@email.com');
    cy.allure().endStep();

    cy.allure().startStep('2.Step two');
    cy.get('.action-disabled').type('disabled error checking', { force: true });
    cy.allure().endStep();
    // ...
  })

```

**Comment by AndriiZhydkykh** [comment]
it('.type() - type into a DOM element', () => {
    cy.allure().startStep('1.Step one');
    cy.get('.action-email').type('fake@email.com').should('have.value', 'fake@email.com');
    cy.allure().endStep();

    cy.allure().startStep('2.Step two');
    cy.get('.action-disabled').type('disabled error checking', { force: true });
    cy.allure().endStep();
    // ...
  })

It does not help. I expected something like this  

![image](https://github.com/mmisty/cypress-allure-adapter/assets/26884857/7f322f19-3731-4185-a166-10611b7246f6)


If I added allureLogCyCommands - true. I will see failed cypress commands but not steps. This can be misleading since it is not clear at what steps the test failed. Especially when the report is viewed by a developer or a manual QA
![image](https://github.com/mmisty/cypress-allure-adapter/assets/26884857/8315de8b-d735-41c2-9f87-9c06fcad83b5)
The command get: .action-disabled which failed is located inside step three, but this step is displayed as passed - with a green checkmark

**Comment by mmisty** [comment]
@AndriiZhydkykh as I can see from your screenshot you still didn't wrap cypress commands by allure steps. You use cy.allure().step() but you need to to use cy.allure().startStep('my step'), 
then add any cypress commands 
and after that you need to end step
by step cy.allure().endStep()

And if some cypress commands fail inside your step then the step will be marked as failed in the report.

**Comment by AndriiZhydkykh** [comment]
@mmisty Yes, forgive my inattention. Thank you, you helped me a lot with your plugin and help.
