### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by AlissonSantana** [mmisty/cypress-allure-adapter#56]
Hi, mmisty, there are a few vulnerabilities on last version of /cypress-allure-adapter, a really appreciate if you check and fix it. 

Thank you.

Examples: https://socket.dev/npm/package/@mmisty/cypress-allure-adapter/issues/0.12.1?tab=dependencies

**Comment by mmisty** [comment]
@AlissonSantana hello,
Thank you for the issue. 

Could you please sent what vulnerability do you see and which one do you want me to fix? 

When I follow your link I see
<img width="1278" alt="image" src="https://github.com/mmisty/cypress-allure-adapter/assets/16957275/721e213b-1674-4ad6-9f4e-9a83c20547f3">

And I don't see any issues in that list that I can quickly fix.

**Comment by mmisty** [comment]
Closing since no response
