### ISSUE TITLE
v0.12.4 onwards global keyword error

### ISSUE THREAD

**Issue by mysticdevx** [mmisty/cypress-allure-adapter#68]
Hi @mmisty 
I have tried to test the Gherkin support by pulling version 0.14.0 after this  https://github.com/mmisty/cypress-allure-adapter/issues/45. However, another bug was introduced as of 0.12.4 and onwards. In v0.12.3, all was ok. The current error screenshot is here:

<img width="938" alt="Screenshot 2023-11-05 at 12 26 16" src="https://github.com/mmisty/cypress-allure-adapter/assets/49609497/881de7ae-10dd-4088-a782-95b9faf759e8">

It seems it was introduced while adding the tags dependency [here](https://github.com/mmisty/cypress-allure-adapter/commit/fcf6e732e0f949920b4944591076a41a1fa46eed). 

If you need a reproducible example, again, I have added to [this](https://github.com/mysticdevx/cy-allure-adapter/tree/latest-version-global-error) repo in a separate branch named "latest-version-global-error"

Thanks.

**Comment by mmisty** [comment]
@mysticdevx hi
Thank you for such a full repro example!

Could you please update your config like it says [here](https://github.com/mmisty/cypress-allure-adapter/blob/HEAD/docs/gherkin.md) and check if that works for you
Latest version with fixes for after/before is 0.14.1

**Comment by mysticdevx** [comment]
Super! Thanks @mmisty. This is also closed :)
Now, there's another minor issue, I'm closing this one and opening a new one for better tracking.
