### ISSUE TITLE
Gherkin steps are logged false in test details

### ISSUE THREAD

**Issue by mysticdevx** [mmisty/cypress-allure-adapter#71]
Description:
In the Gherkin test report scenario details, some steps are logged as failed, although they are passing, and some vice versa. This is reproducible in my sample repo [here](https://github.com/mysticdevx/cy-allure-adapter/tree/main), and also in the cucumber tests included in the plugin package. 

Please see below 2 screenshots:

<img width="1129" alt="Screenshot 2023-11-06 at 12 05 23" src="https://github.com/mmisty/cypress-allure-adapter/assets/49609497/e23035ad-f949-4629-aca4-bcb41632e2f1">

<img width="1157" alt="Screenshot 2023-11-06 at 11 42 37" src="https://github.com/mmisty/cypress-allure-adapter/assets/49609497/422963a2-7916-46a5-a7d1-b989630fce3d">

**Cypress**: 13.4.0
**Node**: 18.16.1
**preprocessor**:   @badeball/cypress-cucumber-preprocessor@19.0.1,
**adapter**: @mmisty/cypress-allure-adapter@0.14.1

Thanks  @mmisty in advance again.

**Comment by mmisty** [comment]
@mysticdevx 
Thank you for report, 

The root cause of this is a known issue - log command shows result of first attempt (in this case it was unsuccessful)
I'll take a look on how to fix that.

**Comment by mysticdevx** [comment]
Thanks @mmisty for the promt response. Just fyi, the SS i've shared from my repo, and the plugin packages report has no retries in these tests. And also, theres another same case in another scenario in the html report, its  nether a retried, nor an outline scenario. But better we shall see afte the bug you have mentioned is resolved.

**Comment by mmisty** [comment]
Sorry for miscommunication- I meant retries of the command, but not test retries

**Comment by mmisty** [comment]
should be fixed in v2.1.0

**Comment by mysticdevx** [comment]
> should be fixed in v2.1.0

@mmisty thanks, i confirm this has been resolved!

**Comment by thomasKuntermannDiva-e** [comment]
thanks a lot! works fine also with 2.3.0
