### ISSUE TITLE
possibility to set custom "historyId" OR make allure-js-commons accessible from Cypress.Allure

### ISSUE THREAD

**Issue by thomasKuntermannDiva-e** [mmisty/cypress-allure-adapter#72]
Hi DEV-team,
I'm currently switched my Cypress framework reporting to your Allure package, because of this issue https://github.com/cypress-io/cypress/issues/27113.
As we are running our tests for our client in Gitlab CI via "matrix" parallelisation (multiple test-domains can execute the same test -> 1 test can have multiple results for 1 pipeline run) and fetching all Job-results to combine them in 1 Allure Report + History afterwards. Until Cypress 12.14, we were using @shelex/cypress-allure-plugin and set a custom Allure "historyId" for each test-execution, depending on with what .cypres-config.ts the test was executed:
in "./cypress/support/e2e.ts"
`
require('@shelex/cypress-allure-plugin')

...

Cypress.Allure.reporter.getInterface().defineHistoryId((title) => {
    return `${Cypress.env('BRAND')}${title}`;
});`

With that we were able to have 1 Allure report with results from one and the same .feature files/tests (Cucumber plugin in use), distinguished per historyId.

Problem now:
- we need to Update Cypress -> the @shellex plugin stopped working (see linked issue above)
- with your package, there is no possibility right now to touch the "historyId" for Allure reports within "Before", "After" hooks or "e2e.ts"
- the Allure result JSON files are all having the same "historyId" for 1 and the same test file 
- this causes Allure Report to only show one of the JSON results, and not all variations (1 variation = 1 test-domain)

Solution?:
1. make it possible in your package to set/overwrite the "historyId" attribute during a test-run via JS/TS code (Before, After hooks or e2e.ts) OR
2. reveal the allure-js-commons Interface from within your package, so that e.g. this code can work again:
`Cypress.Allure.reporter.getInterface().defineHistoryId((title) => {
    return `${Cypress.env('BRAND')}${title}`;
});`

Thanks in advance and looking forward to get our issues resolved :)

Best regards

Thomas

**Comment by mmisty** [comment]
Hello @thomasKuntermannDiva-e 
I created PR, will be added shortly once tests are passed

**Comment by mmisty** [comment]
Added in version 0.15.0

**Comment by thomasKuntermannDiva-e** [comment]
@mmisty  THANK YOU VERY MUCH :) 
I tried setting  cy.allure().historyId in Before() hook and it works like a charme! Reports are generated perfectly again.

And thanks for the quick support!

Best regards

Thomas

**Comment by mmisty** [comment]
@thomasKuntermannDiva-e thank you!
By the way, you can use hooks like 
```
Cypress.Allure.on('test:started' , test => {
  // meat info using Cypess.Allure interface
});
```
this way tests that were not started when `before` failures occur will have all their metadata (this hook executes anyway event when `before` fails

**Comment by thomasKuntermannDiva-e** [comment]
this does not work on my project. If I add
`Cypress.Allure.on('test:started' , test => {
  // meat info using Cypess.Allure interface
});`

to my e2e.ts, the result.json contains a default reference to the caller function "before all hook". see "fullName" & "historyId".
- WRONG
<img width="808" alt="Bildschirmfoto 2023-11-10 um 14 36 56" src="https://github.com/mmisty/cypress-allure-adapter/assets/27360136/e40c737f-4c49-4b32-9f3a-ff954dee3c7c">

The expected values contain a BRAND-XYZ reference (i replaced real value to hide my clients data) + the .feature test-name:
- EXPECTED
<img width="653" alt="Bildschirmfoto 2023-11-10 um 14 40 45" src="https://github.com/mmisty/cypress-allure-adapter/assets/27360136/876034e7-3fb0-4419-846d-ba95904809d8">

But this is nothing we should focus on right now :) just wated to give feedback to your suggestion.

Cheers

Thomas

**Comment by mmisty** [comment]
@thomasKuntermannDiva-e 
The function in the hook is synchronous and you need to use `Cypress.Allure` instead `cy.allure()`

```
Cypress.Allure.on('test:started' , test => { 
  Cypress.Allure.parentSuite(Cypress.env('BRAND').toUpperCase());
  Cypress.Allure.fullName(Cypress.env('BRAND').toUpperCase() + ' # ' + Cypress.currentTest.title);
  Cypress.Allure.historyId(Cypress.env('BRAND').toUpperCase() + ' # ' + Cypress.currentTest.title) 
});
```
