### ISSUE TITLE
Possibility of packing parameters

### ISSUE THREAD

**Issue by Paprikh7** [mmisty/cypress-allure-adapter#90]
Hello ,

I hope this message finds you well. I am reaching out to discuss an enhancement request for your plugin, which our testing team has been actively using. The current setup serves our needs well, but we've identified an opportunity to further improve the reporting capabilities.

The challenge we are facing is related to the number of parameters in our test reports. Currently, there are 30 parameters and more, and organizing them within the report has become a bit cumbersome. We were wondering if it would be possible to implement a feature that allows for better organization of these parameters, perhaps by grouping them into a folder-like structure within the report.

This enhancement would greatly benefit our testing team, as it would make the reports more streamlined and easier to navigate. It would also contribute to a more efficient testing process overall.

If you have any questions or would like further clarification on this request, please feel free to reach out. We appreciate your dedication to maintaining and improving your plugin, and we believe that this enhancement will make a positive impact on its usability.

Thank you for your time and consideration.
<img width="1840" alt="improvement" src="https://github.com/mmisty/cypress-allure-adapter/assets/109957805/e264dc27-3b95-4562-80a5-98c08f4d3db1">

**Comment by mmisty** [comment]
Hi @Paprikh7 , 
If you want to use report parametners there is no way to group them since this is built-in feature in the  allure report.
Although you can do something on your side: 

You can add html description to your test with collapsible section like: 
```javascript
  const html = [
    '<details>',
    '  <summary style="cursor:pointer;">',
    `    <b>Test parameters</b>`,
    '  </summary>',
    '  <ol>',
    '    <li>item 1: value1</li>',
    '    <li>item 2: value2</li>',
    '  </ol>',
    '</details>',
  ].join('\n');

  cy.allure().addDescriptionHtml(html); // or Cypress.allure().addDescriptionHtml(html);
```
